fx_version 'cerulean'
game 'gta5'
lua54 'yes'

author 'Forge Devs - PierreMoraes'
description 'Core System for dedicated qbx'
version '1.1.0'

shared_scripts {
    '@ox_lib/init.lua',
    '@pr_bridge/init.lua',
    'shared/config.lua',
    'shared/job.lua',
    'shared/player.lua',
    'shared/afk.lua',
    'shared/password.lua',
    'shared/weather.lua',
    'shared/whitelist.lua',
    'shared/density.lua',
    'shared/weapons.lua',
    'shared/inventory.lua',
    'shared/skills.lua',
    'shared/staff.lua',
    'shared/multijob.lua',
    'shared/vinewood.lua',
    'shared/objects.lua',
    'shared/npcs.lua',
    'shared/npcs_animations.lua',
    'shared/npcs_peds.lua',
    'shared/spotlights.lua',
    'shared/billboards.lua',
    'shared/stores.lua',
    'shared/farms.lua',
    'shared/starterpack.lua',
    'shared/sit.lua',
}

client_scripts {
    'client/job/state.lua',
    'client/job/points.lua',
    'client/job/business.lua',
    'client/objects/main.lua',
    'client/npcs/main.lua',
    'client/spotlights/main.lua',
    'client/billboards/main.lua',
    'client/stores/main.lua',
    'client/farms/main.lua',
    'client/starterpack/main.lua',
    'client/sit/main.lua',
    'client/menu/menu.lua',
    'client/menu/menu_job.lua',
    'client/menu/menu_business.lua',
    'client/menu/menu_mei.lua',
    'client/menu/menu_skills.lua',
    'client/menu/menu_staff.lua',
    'client/menu/menu_server.lua',
    'client/menu/menu_weather.lua',
    'client/menu/menu_whitelist.lua',
    'client/menu/menu_density.lua',
    'client/menu/menu_weapons.lua',
    'client/menu/menu_inventory.lua',
    'client/menu/menu_vinewood.lua',
    'client/menu/menu_objects.lua',
    'client/menu/menu_npcs.lua',
    'client/menu/menu_spotlights.lua',
    'client/menu/menu_billboards.lua',
    'client/menu/menu_stores.lua',
    'client/menu/menu_farms.lua',
    'client/menu/menu_starterpack.lua',
    'client/menu/menu_multijob.lua',
    'client/menu/menu_player.lua',
    'client/menu/menu_bindings.lua',
    'client/whitelist/main.lua',
    'client/density/main.lua',
    'client/vinewood/main.lua',
    'client/job/creator.lua',
    'client/job/main.lua',
    'client/main.lua',
}

server_scripts {
    'server/job/storage.lua',
    'server/job/registry.lua',
    'server/job/qbx_sync.lua',
    'server/job/points.lua',
    'server/job/business.lua',
    'server/job/service.lua',
    'server/job/payments.lua',
    'server/job/callbacks.lua',
    'server/job/commands.lua',
    'server/player/callbacks.lua',
    'server/weapon/storage.lua',
    'server/weapon/registry.lua',
    'server/weapon/qbx_sync.lua',
    'server/weapon/ox_sync.lua',
    'server/weapon/service.lua',
    'server/weapon/callbacks.lua',
    'server/weapon/commands.lua',
    'server/inventory/service.lua',
    'server/inventory/callbacks.lua',
    'server/skill/storage.lua',
    'server/skill/registry.lua',
    'server/skill/service.lua',
    'server/skill/callbacks.lua',
    'server/skill/commands.lua',
    'server/staff/service.lua',
    'server/staff/callbacks.lua',
    'server/staff/commands.lua',
    'server/afk/service.lua',
    'server/afk/callbacks.lua',
    'server/password/service.lua',
    'server/password/callbacks.lua',
    'server/weather/callbacks.lua',
    'server/whitelist/service.lua',
    'server/whitelist/callbacks.lua',
    'server/density/service.lua',
    'server/density/callbacks.lua',
    'server/multijob/service.lua',
    'server/multijob/callbacks.lua',
    'server/vinewood/service.lua',
    'server/vinewood/callbacks.lua',
    'server/objects/service.lua',
    'server/objects/callbacks.lua',
    'server/objects/commands.lua',
    'server/npcs/service.lua',
    'server/npcs/callbacks.lua',
    'server/npcs/commands.lua',
    'server/spotlights/service.lua',
    'server/spotlights/callbacks.lua',
    'server/billboards/service.lua',
    'server/billboards/callbacks.lua',
    'server/stores/service.lua',
    'server/stores/callbacks.lua',
    'server/farms/service.lua',
    'server/farms/callbacks.lua',
    'server/starterpack/service.lua',
    'server/starterpack/callbacks.lua',
    'server/starterpack/commands.lua',
    'server/plugins.lua',
    'server/menu.lua',
    'server/main.lua',
}

dependencies {
    'ox_lib',
    'pr_bridge',
    'qbx_core',
    'ox_inventory',
}

data_file 'DLC_ITYP_REQUEST' 'stream/**/*.ytyp'

files {
    'stream/**/*.ytyp',
    'data/*.json',
    'locale/*.lua',
}
