ForgeCore = ForgeCore or {}
local Menu,Shared=ForgeCore.Client.Menu,ForgeCore.Client.MenuShared
local function fetchTiers()local ok,data=Shared.awaitServer(PR.Vip.Callbacks.getTiers);if not ok then Shared.notifyFailure('notify.player.load_failed',data);return nil end;return data or {}end
local function options(tiers)local result={};for _,tier in ipairs(tiers or {})do result[#result+1]={value=tier.id,label=tier.label}end;return result end
local function boolOptions()return {{value='true',label='Sim'},{value='false',label='Não'}}end
local function editTier(tier)
    tier=tier or {salary={}};local result=Shared.inputDialog(tier.id and 'Editar classe VIP' or 'Criar classe VIP',{
        {type='input',label='ID interno',default=tier.id,required=true,disabled=tier.id~=nil},{type='input',label='Nome',default=tier.label,required=true},{type='color',label='Cor',default=tier.color or '#ffffff',required=true},{type='input',label='Principal ACE',default=tier.principal,required=true},{type='number',label='Slots extras',default=tier.slots or 0,min=0,required=true},{type='number',label='Peso extra (gramas)',default=tier.weight or 0,min=0,required=true},{type='number',label='Multiplicador de XP',default=tier.xpMultiplier or 1,min=1,step=0.05,required=true},{type='select',label='Salário',options=boolOptions(),default=tier.salary and tier.salary.enabled and 'true' or 'false',required=true},{type='select',label='Moeda do salário',options={{value='money',label='Money'},{value='bank',label='Bank'},{value='crypto',label='Crypto'},{value='coin',label='Coin'}},default=tier.salary and tier.salary.account or 'bank',required=true},{type='number',label='Valor do salário',default=tier.salary and tier.salary.amount or 0,min=0,required=true},
    });if not result then return Menu.openVipClassesMenu()end
    local ok,err=Shared.awaitServer(PR.Vip.Callbacks.saveTier,{id=tier.id or result[1],label=result[2],color=result[3],principal=result[4],slots=result[5],weight=result[6],xpMultiplier=result[7],salary={enabled=result[8]=='true',account=result[9],amount=result[10]}});if not ok then Shared.notifyFailure('notify.player.load_failed',err)end;SetTimeout(400,function()Menu.openVipClassesMenu()end)
end
function Menu.openVipClassesMenu(parent)
    local tiers=fetchTiers();if not tiers then return end;local opts={{title='Criar classe VIP',description='Configure nome, inventário, salário e XP Booster.',icon='plus-circle-fill',onSelect=function()editTier(nil)end}}
    for _,entry in ipairs(tiers)do local tier=entry;opts[#opts+1]={title=tier.label,description=('+%s slots | +%.1f kg | XP %.2fx | Salário: %s %s'):format(tier.slots,(tier.weight or 0)/1000,tier.xpMultiplier,tier.salary.account,tier.salary.amount),icon='star-fill',iconColor=tier.color,metadata={{label='ID',value=tier.id},{label='ACE',value=tier.principal},{label='Salário',value=tier.salary.enabled and 'Ativo' or 'Desativado'}},arrow=true,onSelect=function()Shared.showContext({id='forge_core_vip_tier',title=tier.label,menu='forge_core_vip_classes',options={{title='Editar',description='Alterar os benefícios desta classe.',icon='pencil-fill',onSelect=function()editTier(tier)end},{title='Remover classe',description='Só é permitido sem jogadores online usando esta classe.',icon='trash-fill',iconColor='#ef4444',onSelect=function()local answer=Shared.alertDialog({header='Remover classe',content='Esta ação remove a configuração da classe VIP.',centered=true,cancel=true});if answer=='confirm'then local ok,err=Shared.awaitServer(PR.Vip.Callbacks.deleteTier,tier.id);if not ok then Shared.notifyFailure('notify.player.load_failed',err)end end;SetTimeout(400,function()Menu.openVipClassesMenu(parent)end)end}}})end}end
    Shared.showContext({id='forge_core_vip_classes',title='Classes VIP',menu=parent or 'forge_core_players_management',options=opts})
end
function Menu.openPlayerVipAdmin(target)
    local ok,current=Shared.awaitServer(PR.Vip.Callbacks.get,target);if not ok then return end;local tiers=fetchTiers();if not tiers then return end
    local opts={{title=current.tier=='standard' and 'Adicionar VIP' or 'Editar VIP',description=current.tier=='standard' and 'Escolha classe e validade.' or ('Atual: %s | Expira: %s'):format(current.label,current.expiresAtFormatted),icon='star-fill',onSelect=function()local form=Shared.inputDialog('VIP do jogador',{{type='select',label='Classe VIP',options=options(tiers),default=current.tier~='standard' and current.tier or nil,required=true},{type='number',label='Validade a partir de agora (dias)',min=1,required=true}});if not form then return Menu.openPlayerVipAdmin(target)end;local saved,err=Shared.awaitServer(PR.Vip.Callbacks.grant,target,form[1],form[2]);if not saved then Shared.notifyFailure('notify.player.load_failed',err)end;SetTimeout(400,function()Menu.openPlayerVipAdmin(target)end)end}}
    if current.tier~='standard'then opts[#opts+1]={title='Remover VIP',description='Volta o jogador para Standard e remove os benefícios.',icon='trash-fill',iconColor='#ef4444',onSelect=function()local answer=Shared.alertDialog({header='Remover VIP',content='Confirma a remoção deste VIP?',centered=true,cancel=true});if answer=='confirm'then local saved,err=Shared.awaitServer(PR.Vip.Callbacks.revoke,target);if not saved then Shared.notifyFailure('notify.player.load_failed',err)end end;SetTimeout(400,function()Menu.openPlayerVipAdmin(target)end)end}end
    Shared.showContext({id='forge_core_player_vip',title='Gerenciar VIP',menu='forge_core_managed_player',options=opts})
end
function Menu.openVipMenu()Menu.openVipClassesMenu('forge_core_players_management')end