PR = PR or {}
PR.Density = PR.Density or {}

PR.Density.Storage = {
    file = 'data/density.json',
}

PR.Density.Callbacks = {
    getSettings = 'forge-core:server:density:getSettings',
    saveSettings = 'forge-core:server:density:saveSettings',
}

PR.Density.Defaults = {
    enabled = true,
    disableAll = false,
    values = {
        parked = 0.8,
        vehicle = 0.0,
        multiplier = 0.8,
        peds = 0.8,
        scenario = 0.0,
    },
    pedPopulationBudget = 3,
    vehiclePopulationBudget = 3,
    disableDispatchServices = true,
    blacklist = {
        enabled = true,
        models = {
            'SHAMAL',
            'LUXOR',
            'LUXOR2',
            'JET',
            'BUZZARD',
            'BUZZARD2',
            'ANNIHILATOR',
            'SAVAGE',
            'RHINO',
            'FIRETRUK',
            'MULE',
            'MAVERICK',
            'BLIMP',
            'AIRTUG',
            'HYDRA',
            'OPPRESSOR',
            'technical3',
            'insurgent3',
            'apc',
            'tampa3',
            'trailersmall2',
            'halftrack',
            'hunter',
            'vigilante',
            'akula',
            'barrage',
            'khanjali',
            'caracara',
            'blimp3',
            'menacer',
            'oppressor2',
            'scramjet',
            'strikeforce',
            'cerberus',
            'cerberus2',
            'cerberus3',
            'scarab',
            'scarab2',
            'scarab3',
            'rrocket',
            'ruiner2',
            'deluxo',
            'mesa2',
            'asea2',
            'emperor3',
            'sadler2',
            'burrito5',
            'stromberg',
            'speedo4',
            'speedo5',
            'savestra',
            'granger2',
            'jb7002',
        },
        scenarioTypes = {
            'WORLD_VEHICLE_AMBULANCE',
            'WORLD_VEHICLE_FIRE_TRUCK',
            'WORLD_VEHICLE_POLICE_BIKE',
            'WORLD_VEHICLE_POLICE_CAR',
            'WORLD_VEHICLE_POLICE',
            'WORLD_VEHICLE_POLICE_NEXT_TO_CAR',
            'WORLD_VEHICLE_SECURITY_CAR',
            'WORLD_VEHICLE_HELI_LIFEGUARD',
            'WORLD_VEHICLE_MILITARY_PLANES_BIG',
            'WORLD_VEHICLE_MILITARY_PLANES_SMALL',
        },
        scenarioGroups = {
            'LSA_Planes',
            'SANDY_PLANES',
            'GRAPESEED_PLANES',
            'ng_planes',
        },
    },
    generatorAreas = {},
}
